name: Update README with Commit Chart

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Commit Chart
        run: |
          curl -o commit-chart.svg "https://ghchart.rshah.org/mhmoudalaskalany"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Debug Commit Chart
        run: |
          cat commit-chart.svg

      - name: Update README
        run: |
          sed -i '/<!-- commit-chart -->/r commit-chart.svg' README.md
          rm commit-chart.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}